services:
  brainz-api:
    build: ./BrainzAPI
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - brainz-auth
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_LESSON_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - appnet
  
  brainz-auth:
    build: ./BrainzAuth
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_AUTH_NAME}
    networks:
      - appnet

  brainz-parser:
    build: ./BrainzParser
    ports:
      - "4444:80"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_LESSON_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - appnet

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - appnet
  
  redis:
    image: redis:8.2.1-alpine
    command: >
      redis-server
      --maxmemory 500mb
      --maxmemory-policy allkeys-lru
      --appendonly no
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "0.5"
    networks:
      - appnet

volumes:
  postgres_data:
  redis_data:

networks:
  appnet:
    driver: bridge